version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'skip-changelog'
      - 'dependencies'
    rebase-strategy: disabled

  - package-ecosystem: npm
    directory: '/'
    allow:
      - dependency-name: cross-fetch

    schedule:
      interval: 'monthly'
      time: '04:00'
    open-pull-requests-limit: 10
    labels:
      - skip-changelog
      - dependencies
    versioning-strategy: increase
    rebase-strategy: disabled
