version: "3.8"

services:
  package:
    image: node:16
    tty: true
    stdin_open: true
    working_dir: /home/package
    environment:
      - MEILISEARCH_URL=http://meilisearch:7700
    depends_on:
      - meilisearch
    links:
      - meilisearch
    volumes:
      - ./:/home/package

  meilisearch:
    image: getmeili/meilisearch:v1.5.0-rc.3
    ports:
      - "7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
