name: publish to npm
on:
  release:
    types: [published]

env:
  HUSKY: 0

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Check release validity
        run: sh .github/scripts/check-release.sh
      - name: Check tag format
        run: sh .github/scripts/check-tag-format.sh "${{ github.event.release.prerelease }}"

      - uses: ./.github/actions/set-up-node
        with:
          registry-url: https://registry.npmjs.org/

      # This will cause pnpm git checks to fail
      - name: Build meilisearch-js
        run: pnpm build
      - name: Publish with latest tag
        if: github.event.release.prerelease == false
        run: pnpm publish --provenance --no-git-checks --access public
      - name: Publish with beta tag
        if: github.event.release.prerelease
        run: pnpm publish --provenance --no-git-checks --access public --tag beta
